In [1]:
# TensorFlow e tf.keras
import tensorflow as tf
from tensorflow import keras

# Wandb
from wandb.keras import WandbCallback
import wandb

# Bibliotecas Auxiliares
import os
import idx2numpy
import gzip
import numpy as np
import matplotlib.pyplot as plt
import config

2022-07-26 11:49:56.389264: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-07-26 11:49:56.949259: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-26 11:49:56.949289: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
os.system(f"wandb login --relogin {config.WandbAcess().WANDB_URL}")

wandb: Appending key for api.wandb.ai to your netrc file: /home/diego/.netrc


0

In [3]:
run = wandb.init(project="mnist_deep_classification",save_code=True,job_type='train')
dataset_train = 'preprocessed_x_train.npz'
artifact_train = run.use_artifact(f"mnist_deep_classification/{dataset_train}:latest",type='npz')
artifact_train.file()


Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: diego25rm. Use `wandb login --relogin` to force relogin


'./artifacts/preprocessed_x_train.npz:v0/preprocessed_x_train.npz'

In [4]:
x_train = np.load(artifact_train.file())['imgs']

In [5]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [6]:
y_dataset_train = 'train-labels-idx1-ubyte.gz'
y_artifact_train= run.use_artifact(f"mnist_deep_classification/{y_dataset_train}:latest",type='gzip')
y_artifact_train.file()


'./artifacts/train-labels-idx1-ubyte.gz:v0/train-labels-idx1-ubyte.gz'

In [7]:
with gzip.open(y_artifact_train.file(), 'r') as f:
    y_train = idx2numpy.convert_from_file(f)


In [8]:
y_dataset_test = 't10k-labels-idx1-ubyte.gz'
y_artifact_test= run.use_artifact(f"mnist_deep_classification/{y_dataset_test}:latest",type='gzip')
y_artifact_test.file()
with gzip.open(y_artifact_test.file(), 'r') as f:
    y_test = idx2numpy.convert_from_file(f)

In [9]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
dataset_test = 'preprocessed_x_test.npz'
artifact_test = run.use_artifact(f"mnist_deep_classification/{dataset_test}:latest",type='npz')
artifact_test.file()
x_test = np.load(artifact_test.file())['imgs']

In [11]:
x_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [12]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(10, activation='softmax')
])


2022-07-26 11:51:19.203783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-07-26 11:51:19.209437: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-26 11:51:19.209950: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-07-26 11:51:19.210478: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-07-26 11:51:19.211474: W tensorflow/stream_executor/platform/default/dso_loader.cc:6

In [13]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [14]:
history = model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.2310 - accuracy: 0.9320
Epoch 2/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1139 - accuracy: 0.9657
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0888 - accuracy: 0.9736
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0712 - accuracy: 0.9781
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0610 - accuracy: 0.9809


In [15]:
def train():
    # Default values for hyper-parameters we're going to sweep over
    defaults = dict(layer_1 = 100,
                layer_2 = 100,
                batch_size = 32,
                learn_rate = 0.001,
                epoch = 20)

    wandb.init(project="mnist_deep_classification",save_code=True,job_type='train', config= defaults)

    # Config is a variable that holds and saves hyperparameters and inputs
    config = wandb.config
    
    # Instantiate a simple classification model
    model = keras.Sequential([
                                keras.layers.Flatten(input_shape=(28, 28)),
                                keras.layers.Dense(config.layer_1, activation='relu', dtype='float64'),
                                keras.layers.BatchNormalization(),
                                keras.layers.Dense(config.layer_2, activation='relu', dtype='float64'),
                                keras.layers.Dense(10, activation='softmax', dtype='float64')
                                ])
    # loss = keras.losses.SparseCategoricalCrossentropy()

    # # Instantiate an accuracy metric.
    # accuracy = keras.metrics.Accuracy()

    # # Instantiate an optimizer.
    # optimizer = keras.optimizers.Adam(learning_rate=config.learn_rate)

    # # configure the optimizer, loss, and metrics to monitor.
    # model.compile(optimizer=optimizer, loss=loss, metrics=[accuracy])  

    # model.fit(x_train, y_train, batch_size=config.batch_size,
    #           epochs=config.epoch,
    #           validation_data=(x_test, y_test))

    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']) 
 
    model.fit(x=x_train,
          y=y_train,
          batch_size=config.batch_size,
          epochs=config.epoch,
          validation_data=(x_test,y_test),
          callbacks=[WandbCallback(log_weights=True)],
          verbose=1)

In [16]:
sweep_config = {
    'method': 'random', #grid, random
    'metric': {
      'name': 'accuracy',
      'goal': 'maximize'   
    },
    'parameters': {
        'layer_1': {
            'max': 130,
            'min': 110,
            'distribution': 'int_uniform',
        },
        'layer_2': {
            'max': 130,
            'min': 110,
            'distribution': 'int_uniform',
        },
        'learn_rate': {
            'max': 0.01, 
            'min': 0.0001,
        },
        'epoch': {
            'values': [20,30,40]
        },
        'batch_size': {
            'values': [32,64]
        }
    }
}

In [17]:
sweep_id = wandb.sweep(sweep_config, entity="diego25rm", project="mnist_deep_classification")

Create sweep with ID: m78xffq3
Sweep URL: https://wandb.ai/diego25rm/mnist_deep_classification/sweeps/m78xffq3


In [18]:
# wandb.agent(sweep_id = sweep_id, function=train,count=15)

In [20]:
best_model = wandb.restore('model-best.h5', run_path="diego25rm/mnist_deep_classification/5u5r18i0")

In [ ]:
# model2 = keras.models.load_model('/mnt/c/Users/diego/Desktop/projeto pdi_machine_learning/projeto-pdi_machine_learning/app/model')


In [22]:
# import cv2
model2 = keras.models.load_model(best_model.name)
predction = model2.predict([x_test])

313/313 [==============================] - 1s 3ms/step


In [23]:
predction

array([[2.43011262e-05, 8.00961110e-06, 1.52962527e-04, ...,
        9.98812376e-01, 5.43274413e-05, 7.92574307e-05],
       [1.70867411e-08, 5.30632241e-06, 9.99994349e-01, ...,
        2.49623722e-08, 3.46194988e-08, 1.16099789e-11],
       [1.09386963e-07, 9.99949656e-01, 7.32826541e-06, ...,
        1.26700727e-05, 2.21817976e-05, 7.05927455e-08],
       ...,
       [2.80754847e-14, 4.73874430e-11, 4.11811158e-12, ...,
        4.55340161e-07, 1.62035722e-10, 6.86505691e-06],
       [8.10959225e-11, 6.50458148e-11, 1.73766987e-12, ...,
        1.38135386e-11, 1.54156567e-06, 1.04134474e-11],
       [4.31729721e-08, 4.39325652e-10, 1.12342658e-07, ...,
        3.52225191e-11, 3.03248619e-09, 2.37668053e-08]])

In [ ]:
# x_test[10].min()

In [ ]:
# predction[1]
# plt.imshow(x_test[10])
# np.argmax(predction[10])
